<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Form extends Model
{
    protected $fillable=[
        'jump',
    'ritualGoodMorning',
    'weightGain',
    'ritualGoodMorningLight',
    'ritualGoodMorningNoise',
    'ritualGoodMorningStimulus',
    'ritualGoodMorningRemove',
    'typeEatingRoutine',
    'routineDifficulties',
    'weightGain',
    'colicObstacle',
    'refluxObstacle',
    'gasObstacle',
    'aplvObstacle',
    'energyExpenditure',
    'noticeSigns',
    'slowDown',
    'ritualType',
    'environmentNapsLights',
    'environmentNapsNoises',
    'environmentNapsTemperature',
    'whereSleepCrib',
    'whereSleepLap',
    'whereSleepLapCrib',
    'whereSleepSharedBed',
    'whereSleepCar',
    'whereSleepRede',
    'whereSleepOther',
    'environmentNapBother',
    'napAssociationWhiteNoise',
    'napAssociationCloth',
    'napAssociationPacifier',
    'napAssociationSuckFinger',
    'napAssociationSuckle',
    'napAssociationOther',
    'enoughNap',
    'wakeUpNap',
    'nightRitual',
    'environmentRitualLights',
    'environmentRitualNoises',
    'environmentRitualTemperature',
    'ritualAssociationWhiteNoise',
    'ritualAssociationCloth',
    'ritualAssociationPacifier',
    'ritualAssociationSuckFinger',
    'ritualAssociationSuckle',
    'ritualAssociationOther',
    'conclusionImmaturity',
    'conclusionHungry',
    'conclusionAche',
    'conclusionJump',
    'conclusionAnguish',
    'conclusionScreens',
    'conclusionStress',
    'comments',
    ];
}
